language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

before_install:
    - sudo apt-get update -q
script: perl Makefile.PL && make test

branches:
  only:
    - master

notifications:
  recipients:
    - spajai@cpan.com

email:
    on_success: change
    on_failure: always
